// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace BowlingWithAI.AcceptanceTests
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ScoreABowlingGameFeature : object, global::Xunit.IClassFixture<ScoreABowlingGameFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "", "Score a bowling game", "  As an avid bowler\n  I want to correctly score a game\n  So that I can see my pro" +
                "gress", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "ScoreBowling.feature"
#line hidden
        
        public ScoreABowlingGameFeature(ScoreABowlingGameFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("ScoreBowling.feature.ndjson", 6);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Score a game of all gutter balls")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Score a bowling game")]
        [global::Xunit.TraitAttribute("Description", "Score a game of all gutter balls")]
        public async global::System.Threading.Tasks.Task ScoreAGameOfAllGutterBalls()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Score a game of all gutter balls", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 6
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await testRunner.GivenAsync("I have rolled gutter balls in every frame", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
  await testRunner.WhenAsync("I calculate the score for this game", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 9
  await testRunner.ThenAsync("I see a score of 0 for this game", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Score a game of all open frames")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Score a bowling game")]
        [global::Xunit.TraitAttribute("Description", "Score a game of all open frames")]
        public async global::System.Threading.Tasks.Task ScoreAGameOfAllOpenFrames()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Score a game of all open frames", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 11
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Roll1",
                            "Roll2"});
                table1.AddRow(new string[] {
                            "1",
                            "7"});
                table1.AddRow(new string[] {
                            "6",
                            "1"});
                table1.AddRow(new string[] {
                            "1",
                            "0"});
                table1.AddRow(new string[] {
                            "3",
                            "0"});
                table1.AddRow(new string[] {
                            "4",
                            "5"});
                table1.AddRow(new string[] {
                            "6",
                            "0"});
                table1.AddRow(new string[] {
                            "5",
                            "3"});
                table1.AddRow(new string[] {
                            "3",
                            "2"});
                table1.AddRow(new string[] {
                            "8",
                            "0"});
                table1.AddRow(new string[] {
                            "3",
                            "4"});
#line 12
  await testRunner.GivenAsync("I have completed the game", ((string)(null)), table1, "Given ");
#line hidden
#line 24
  await testRunner.WhenAsync("I calculate the score for this game", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 25
  await testRunner.ThenAsync("I see a score of 62 for this game", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Score a game of both open frames and spares")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Score a bowling game")]
        [global::Xunit.TraitAttribute("Description", "Score a game of both open frames and spares")]
        public async global::System.Threading.Tasks.Task ScoreAGameOfBothOpenFramesAndSpares()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Score a game of both open frames and spares", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 27
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "Roll1",
                            "Roll2"});
                table2.AddRow(new string[] {
                            "3",
                            "0"});
                table2.AddRow(new string[] {
                            "8",
                            "1"});
                table2.AddRow(new string[] {
                            "8",
                            "2"});
                table2.AddRow(new string[] {
                            "0",
                            "10"});
                table2.AddRow(new string[] {
                            "6",
                            "0"});
                table2.AddRow(new string[] {
                            "7",
                            "0"});
                table2.AddRow(new string[] {
                            "8",
                            "2"});
                table2.AddRow(new string[] {
                            "2",
                            "0"});
                table2.AddRow(new string[] {
                            "9",
                            "0"});
                table2.AddRow(new string[] {
                            "2",
                            "4"});
#line 28
  await testRunner.GivenAsync("I have completed the game", ((string)(null)), table2, "Given ");
#line hidden
#line 40
  await testRunner.WhenAsync("I calculate the score for this game", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 41
  await testRunner.ThenAsync("I see a score of 80 for this game", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Score a game of strikes, spares, and open frames")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Score a bowling game")]
        [global::Xunit.TraitAttribute("Description", "Score a game of strikes, spares, and open frames")]
        public async global::System.Threading.Tasks.Task ScoreAGameOfStrikesSparesAndOpenFrames()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Score a game of strikes, spares, and open frames", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 43
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "Roll1",
                            "Roll2"});
                table3.AddRow(new string[] {
                            "6",
                            "0"});
                table3.AddRow(new string[] {
                            "5",
                            "2"});
                table3.AddRow(new string[] {
                            "10",
                            ""});
                table3.AddRow(new string[] {
                            "3",
                            "7"});
                table3.AddRow(new string[] {
                            "9",
                            "0"});
                table3.AddRow(new string[] {
                            "6",
                            "4"});
                table3.AddRow(new string[] {
                            "10",
                            ""});
                table3.AddRow(new string[] {
                            "7",
                            "3"});
                table3.AddRow(new string[] {
                            "3",
                            "4"});
                table3.AddRow(new string[] {
                            "1",
                            "5"});
#line 44
  await testRunner.GivenAsync("I have completed the game", ((string)(null)), table3, "Given ");
#line hidden
#line 56
  await testRunner.WhenAsync("I calculate the score for this game", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 57
  await testRunner.ThenAsync("I see a score of 127 for this game", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await ScoreABowlingGameFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await ScoreABowlingGameFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
